fun main() {
    println("Hello world")
    println("Hello world1")
    println("Hello world2")
    println("Hello world3")
    println("Hello world4")
    println("Hello world5")
    println("Hello world6")
    println("Hello world7")
    println("Hello world8")
    println("Hello world9")
    println("Hello world10")
    println("Hello world11")
    println("Hello world12")
    println("Hello world13")
    println("Hello world14")
    println("Hello world15")
}